### ISSUE TITLE
Missing ANBI data

### ISSUE THREAD

**Issue by Threore** [dwh-outsite/dwhdelft.nl#20]
Per [anbi.nl/publicatieverplichting](https://anbi.nl/publicatieverplichting/ ) the ANBI page should contain the following items that are not currently present:

**Post- of bezoekadres, dan wel het telefoonnummer, dan wel het e-mailadres van de instelling;**
This is currently only in the footer, which technically is sufficient but listing all on the ANBI page itself would be better.

**Doelstelling volgens de statuten en andere interne regelgeving;**
I'm fine with the altered LGBT+ version as "interne regelgeving", but the statutory version needs to be there as well, I suggest simply linking the statutes like on the old ANBI page.

**Bestuurssamenstelling, het beloningsbeleid van de instelling en de namen van de bestuurders**
This is missing. There are exceptions for the requirement to publish by the way, we could look into those as they could apply to us and allow us to have board members who remain anonymous to the outside world.

**Comment by casperboone** [comment]
* Beloningsbeleid, bestuurssamenstelling and the names of board members are all present on the current ANBI page (partly in the footer, intentionally)
* Contact stuff is intentionally only in the footer, but still on the same page. This is to avoid duplication. If you look at the old ANBI page you see that a lot of stuff is outdated, the board members were not even updated until a few months ago. I'd like to avoid this situation. With the current solution we still comply with the rules and avoid this situation.
* Doelstelling. I based the page's content on [this, by the Rijksoverheid](https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/bijzondere_regelingen/goede_doelen/algemeen_nut_beogende_instellingen/gegevens_van_een_anbi_publiceren_op_een_internetsite/gegevens_van_een_anbi_publiceren_op_een_internetsite). Here it doesn't explicitly state that this has to come from the statutes. However, we could still link them I guess. I'd suggest putting them in the `DWH/Website` drive folder, and linking that here.

**Comment by Threore** [comment]
Fair enough. I mostly wanted to make sure you were aware of these points, and I think your reasoning is reasonable (🤔).
