### ISSUE TITLE
Manifest meta already provided! warning

### ISSUE THREAD

**Issue by ARBaart** [dwh-outsite/dwhdelft.nl#27]
This is because Nuxt already generates one, see [here](https://pwa.nuxtjs.org/modules/manifest.html) and we do the same manually in the headers.

We could change this by adding the following to `next.config.js`
```
  pwa: {
    manifest: {
      "name": "DWH",
      "short_name": "DWH",
      (...)
    }
  },
```
which would add the information from `static/site.webmanifest` and removing the line
```
      { rel: 'manifest', href: '/site.webmanifest' },
```

However, it also adds some other fields that presumably are by default in the Nuxt manifest, and the simple version of just copying `site.webmanifest` into `pwa.manifest` turned icons into an empty array...

I haven't found a way to solve it the other way around, by removing the default manifest, so perhaps we'll have to live with this warning.

**Comment by casperboone** [comment]
Fixed in #59
