### ISSUE TITLE
Add group photo or individual photos + bios to education page

### ISSUE THREAD

**Issue by ARBaart** [dwh-outsite/dwhdelft.nl#357]
To make that page more personal.

**Comment by casperboone** [comment]
We need content for that first :)

**Comment by ARBaart** [comment]
**Dante**
![voorlichter-dante](https://user-images.githubusercontent.com/643200/211193969-7eb41ec7-7d63-4b96-9708-df873c408a58.jpg)
Heeyhey, ik ben Dante en ben net begonnen bij de voorlichting. Zelf gaf ik al voorlichting op mijn middelbare school en daar merkte ik hoeveel positieve impact het voor iemand kan hebben als er open over LGBTQ+ zaken gepraat wordt 🧡 Ook was het voor mij persoonlijk fijn geweest als er een keer iemand had verteld dat non-binaire mensen bestaan 😅 dus nu doe ik dat zelf 😇 xoxo Dante

**Stefan**
![voorlichter-stefan](https://user-images.githubusercontent.com/643200/211193972-cd52e737-159a-4b1e-a11e-36b39c4deae4.jpg)
Hoi! Ik ben Stefan, 26 jaar, en sinds enkele jaren actief als voorlichter in mijn geliefde Delft. Ik vind het belangrijk om voorlichting te geven omdat ik dit zelf gemist heb tijdens mijn schooltijd. Ik ben ervan overtuigd dat dit mijn coming-out proces een stuk makkelijker gemaakt zou hebben. Enkel het taboe doorbreken door erover te praten kan al het verschil maken in iemands leven. Daar doe ik het voor!

**Jeroen E**
![voorlichter-jeroen](https://user-images.githubusercontent.com/643200/211193971-52edf010-d67b-4856-b5c5-bef69ef42bda.jpg)
Ik ben Jeroen en geef voorlichting sinds 2008. Ik ben voorlichting gaan geven omdat ik het belangrijk vind om leerlingen een meer realistisch beeld te geven en het stereotype beeld wat je op tv ziet en hun vooroordelen te doorbreken. Ik vind het leuk als je tijdens de les dit beeld ziet veranderen doordat ze met elkaar in gesprek gaan.

**Comment by ARBaart** [comment]
@casperboone Added the content <3
