### ISSUE TITLE
Missing menu items

### ISSUE THREAD

**Issue by ARBaart** [dwh-outsite/dwhdelft.nl#392]
The top menu of the DWH site should have many items that are now only in the footer or not anywhere, e.g.

- Vereniging
  - Over ons
  - Word lid
  - Barbuddy
  - My DWH
  - Andersblad
- Activiteiten
  - ...
- Jeugd
  - Outsite
  - Jong&Out
  - KMG
- Maatschappelijk
  - Voorlichting
  - Resources

or something like that. I don't have a great idea for the exact division of items but I feel a bunch are at least missing right now.

**Comment by casperboone** [comment]
The site has a non-nested menu structure on purpose, not really in favor of changing that.

I don't think there are any pages that are "not anywhere", except for the chat groups (on purpose), or am I missing something?
