### ISSUE TITLE
WhatsApp form announcements chat

### ISSUE THREAD

**Issue by ARBaart** [dwh-outsite/dwhdelft.nl#396]
Since there are such chats now for DWH and MIXUP as well, I feel like the form should be changed to add a:

() all announcements
() some announcements:
  [] DWH
  [] Outsite
  [] MIXUP

or something, and it should be on the DWH site too

**Comment by casperboone** [comment]
Hi, this issue has been stale for a long time. Please reopen the issue if it's still relevant.
