### ISSUE TITLE
Add engine requirements for npm/node

### ISSUE THREAD

**Issue by thomcsmits** [dwh-outsite/dwhdelft.nl#514]
Nuxt is yet not compatible with Node.js v20 ([issue](https://github.com/nuxt/nuxt/issues/20445)).

It is nice to add this to the package.json file like [this](https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json).

**Comment by Drew-Macgibbon** [comment]
Hi, just letting you know this was resolved here: [pr](https://github.com/nuxt/nuxt/pull/20472)
