### ISSUE TITLE
Outsite gekke driehoek in footer

### ISSUE THREAD

**Issue by laurensWe** [dwh-outsite/dwhdelft.nl#541]
Het is niet zo dat het in het footer element zit, maar het is van de doorlopende achtergrond. Dus of we moeten er iets van een blok boven de footer doen of de achtergrond aanpassen. Just saying deze specifieke bevinding

**Comment by casperboone** [comment]
@laurensWe Jenna is/was hiermee bezig 😊

**Comment by laurensWe** [comment]
Closed vanwege de rewrite en upgrade naar nuxt3
