### ISSUE TITLE
Lists with people have capacity from styling component

### ISSUE THREAD

**Issue by thomcsmits** [dwh-outsite/dwhdelft.nl#551]
E.g. voorlichters has a maximum of 5 because otherwise the voorlichter overlaps with the 'interesse in voorlichting'. 
It's good to have a maximum, but it'd be nice if it could be more flexible.
Perhaps we can have flexible styling (e.g. size of the purple block behind it).

<img width="665" alt="screenshot of voorlichters, with 6 people, where the last overlaps with the next block" src="https://github.com/dwh-outsite/dwhdelft.nl/assets/90332819/d794c38c-6987-42e5-bffa-e54349dd1a60">

**Comment by casperboone** [comment]
Hm, this was kind of designed like that on purpose. Is it possible to return to an odd number of educators here?

**Comment by thomcsmits** [comment]
Ah alright! Good to know, I'll add another person
